# Generated by Django 5.1.6 on 2025-02-18 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('type', models.BooleanField(default=True)),
                ('wallet_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wallet', to_field='wallet_uuid')),
            ],
        ),
    ]
