# Generated by Django 5.1.6 on 2025-02-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='operation',
            field=models.CharField(choices=[('D', 'DEPOSIT'), ('W', 'WITHDRAW')], default='D', max_length=1),
            preserve_default=False,
        ),
    ]
