# Generated by Django 5.1.6 on 2025-02-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_wallet_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='operation',
            new_name='operationType',
        ),
    ]
